name: Laberinto
main: bombaP.LaberintoPlugin
author: [Autor]
description: Sin descripcion de momento...
version: 1.0
commands:  
   laberinto:
      description: Construye una casa chula.
      usage: /<command> [bomba_nuclear]