name: Arquito
main: PackAge.Plugin
author: [Autor]
description: Sin descripcion de momento...
version: 1.0
commands:  
   arcoteletransportador:
      description: arco
      usage: /command [Arco activado/desactivado]